# infection parameters
outside_household_infectivity_scaling: (float) Controls how likely an outside household contact is to infect
overdispersion: (float) The overdispersion in the social contact distribution
asymptomatic_prob: (float) The probability that an infection is asymptomatic
asymptomatic_relative_infectivity: (float) How infectious an asymptomatic is relative to a symptomatic per contact
infection_reporting_prob: (float) The probability that a symptomatic case reports their infection and tries to get tested
household_pairwise_survival_prob: (float) The per edge probability of transmission within a household
reduce_contacts_by: (float, optional) Apply some level of social distancing. If a list is passed, then various levels of social distancing are applied to different households. Defaults to 0.
prob_has_trace_app: (float, optional) What proportion of the population have the contact tracing app, if their household has the propensity to use the app. Defaults to 0.
hh_propensity_to_use_trace_app: (float, optional) What proportion of households are likely to use the contact tracing app. Defaults to 1.
test_before_propagate_tracing: (bool, Optional) Whether testing is done on symptom onset (False) or after a test result (True). Defaults to True.
starting_infections: (int, optional) The number of infections at time = 0. Defaults to 1.
transmission_probability_multiplier: (float, optional) multiplier to reflect increased probability of transmission of new variant(s) relative to parameers estimated with early/mid 2020 data ]

#Isolation parameters
quarantine_duration: (int, optional) number of days that contacts will quarantine (also referred to as 'isolation' in the UK) if they are contacts of a case.
self_isolation_duration: (int, optional) number of days a case will self-isolate post symptom onset if they report their infection.

#Adherence parameters
node_will_uptake_isolation_prob: (float, optional) Probability that a node will adhere and uptake isolation when required. Defaults to 1.
propensity_imperfect_quarantine: (float, optional)
global_contact_reduction_imperfect_quarantine: (float, optional)

#Household parameters
house_size_probs: (Optional) Probability of each household size

# contact tracing parameters
contact_tracing_success_prob: (float) The probability that a contact tracing attempt succeeds
contact_trace: (bool) Whether to contact trace or not
do_2_step: (bool, optional) Whether to use two step tracing on the households. Defaults to False.

