from pyvis.network import Network as pvNetwork
import networkx as nx


from household_contact_tracing.views.simulation_view import SimulationView
from household_contact_tracing.network import Network
from household_contact_tracing.simulation_model import SimulationModel
from household_contact_tracing.views.colors import node_colours, edge_colours


class GraphPyvisView(SimulationView):
    """Graph View using Pyvis library:
        https://pyvis.readthedocs.io/en/latest/tutorial.html
    """
    def __init__(self, controller, model: SimulationModel):
        # Viewers own copies of controller and model (MVC pattern)
        # ... but controller not required yet (no input collected from view)
        # self.controller = controller
        self.model = model

        # Register as observer
        self.model.register_observer_state_change(self)
        self.model.register_observer_simulation_stopped(self)

    def set_display(self, show: bool):
        if show:
            self.model.register_observer_state_change(self)
            self.model.register_observer_simulation_stopped(self)
        else:
            self.model.remove_observer_state_change(self)
            self.model.remove_observer_simulation_stopped(self)

    def model_param_change(self, subject):
        """ Respond to parameter change(s) """
        pass

    def model_state_change(self, subject):
        """ Respond to changes in model state (e.g. running, extinct, timed-out) """
        pass

    def model_step_increment(self, subject):
        """ Respond to single step increment in simulation """
        pass

    def model_simulation_stopped(self, subject: SimulationModel):
        if self not in subject._observers_graph_change:
            self.draw_network(subject.network)

    def graph_change(self, subject: SimulationModel):
        """ Respond to changes in graph (nodes/households network) """
        self.draw_network(subject.network)

    def set_show_all_graphs(self, show_all):
        if show_all:
            self.model.register_observer_graph_change(self)
        else:
            self.model.remove_observer_graph_change(self)

    def draw_network(self, network: Network):
        """Draws the network generated by the model."""

        nt = pvNetwork('1000px', '1000px')

        reduced_graph = self._adapt_nodes(network.graph)
        # populates the nodes and edges data structures
        nt.from_nx(reduced_graph)
        #nt.show_buttons(filter_=['physics'])
        nt.show_buttons()
        nt.show('nx.html')

    def _adapt_nodes(self, graph: nx.Graph):
        result = graph.copy()

        for node in list(result.nodes(data=True)):
            # Add the required info to the graph for rendering
            result.nodes[node[0]]['label'] = node[1]['node_obj'].household.house_id
            result.nodes[node[0]]['group'] = node[1]['node_obj'].node_type().value
            result.nodes[node[0]]['color'] = node_colours[node[1]['node_obj'].node_type()].colour
            result.nodes[node[0]]['title'] = node_colours[node[1]['node_obj'].node_type()].label

            # Remove the Node object from the graph node, as pyvis can't handle non JSON-serialisable objects
            node[1].pop('node_obj')

        for edge in result.edges.data():
            # For full set of edge settings, see: https://visjs.github.io/vis-network/docs/network/edges.html
            # Add the required info to the graph for rendering
            edge[2]['color'] = edge_colours[edge[2]['edge_type']].colour
            edge[2]['title'] = edge_colours[edge[2]['edge_type']].label

            # Too crowded (diagram) with labels on edges, but leaving in, in case required
            # edge[2]['label'] = edge_colours[edge[2]['edge_type']].label
            # edge[2]['font.size'] = '8'

            # Remove the Node object from the graph node, as pyvis can't handle non JSON-serialisable objects
            edge[2].pop('edge_type')

        return result
